[links]
distillate = "https://telegra.ph/CHto-takoe-gidrolat-02-11"
prices = "https://telegra.ph/Gde-posmotret-assortiment-i-ceny-02-10"
soap = "https://telegra.ph/CHto-takoe-kraftovoe-mylo-02-09"
ubtan = "https://telegra.ph/CHto-takoe-Ubtan-02-25-2"